### ISSUE TITLE
Add GitHub release

### ISSUE THREAD

**Issue by baimafeima** [hybridtupel/WrittenClock#1]
Hi Marian, I am curious how WrittenClock works. Does it come with a GUI? Could you add a release here on GitHub? Many thanks.

**Comment by mbaeuerle** [comment]
Yes the clock does come with a GUI. I try to add a release in the next couple of days!

**Comment by mbaeuerle** [comment]
I just made a release, you can find it here: https://github.com/mbaeuerle/WrittenClock/releases/tag/v1.0.1
I am sorry for all the parts written in german, if you have questions don't hesitate to ask!

**Comment by baimafeima** [comment]
Thanks a lot for the updates. Looks great!
